name: Documentation Quality Check

on:
  push:
    paths:
      - 'docs/**'
      - 'yarp/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/docs-check.yml'
  pull_request:
    paths:
      - 'docs/**' 
      - 'yarp/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/docs-check.yml'

jobs:
  docs-check:
    name: Documentation Quality Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx>=7.1.0 sphinx-rtd-theme>=2.0.0
        
    - name: Check documentation builds without errors
      run: |
        cd docs
        sphinx-build -b html source build -W --keep-going
        
    - name: Check for broken links
      run: |
        cd docs
        sphinx-build -b linkcheck source build || echo "Link check completed with warnings"
        
    - name: Check documentation coverage
      run: |
        cd docs
        sphinx-build -b coverage source build
        if [ -f build/coverage/python.txt ]; then
          echo "Documentation coverage report:"
          cat build/coverage/python.txt
        fi
        
    - name: Upload build artifacts (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: docs-build-failure
        path: |
          docs/build
          !docs/build/.doctrees